Add jvm-jersey library
fission/fission-java-libs pull request #2
Opened 2020-07-29 06:43 UTC by sahil-lakhwani

Signed-off-by: sahil-lakhwani <sahilakhwani@gmail.com>

This PR adds a new package for functions to work with JVM-Jersey environments.

It also modifies the current package name from `fission-java-core` to `fission-java-spring` to avoid any confusions.

2020-08-06 09:09 UTC, vishal-biyani requested changes
Apart from the issues around backward compatibility - which means we should not rename `fission-java-core` to `fission-java-spring` - anywhere I think this PR is fine. I will approve it once I have tried the jersey environment.

2020-08-06 09:09 UTC, vishal-biyani commented on fission-java-jersey/pom.xml
> +      <organizationUrl>https://platform9.com/</organizationUrl>
Please remove this reference - instead add InfraCloud reference

2020-08-06 09:09 UTC, vishal-biyani commented on fission-java-spring/pom.xml
> +  <artifactId>fission-java-spring</artifactId>
In order to support backward compatibility - we should let `fission-java-core` be as it is

2020-08-20 06:25 UTC, vishal-biyani requested changes
Hey @sahil-lakhwani there is some clean up needed:
1. FissionContext from java-core has been deleted (Need not be)
2. .gitignore moved out from java-core (need to be in both places)
3. I still see some fission-java-spring folder
4. Same with Function - we don't need to delete the old one but one change does that.

Can we please get this fixed?

2020-08-21 10:29 UTC, sahil-lakhwani commented
> Hey @sahil-lakhwani there is some clean up needed:
> 
>     1. FissionContext from java-core has been deleted (Need not be)
> 
>     2. .gitignore moved out from java-core (need to be in both places)
> 
>     3. I still see some fission-java-spring folder
> 
>     4. Same with Function - we don't need to delete the old one but one change does that.
> 
> 
> Can we please get this fixed?

1 & 4 are done to keep the class and interface names in sync with our artifacts

I have changed the folder name to `fission-java-core`, as it was
Also, the new environment artifact is named `fission-jvm-jersey` with version `0.0.1`

2020-08-21 16:26 UTC, merged

2020-08-21 16:26 UTC, vishal-biyani commented
Thanks @sahil-lakhwani this looks good!